import './globals.css';
import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme-provider';
import { ThemeToggle } from '@/components/theme-toggle';

// mocking: start mock server
// msw still not working with nextjs 13
// if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
//   require('../mocks');
// }

// theming: import fonts, check back tailwind config: https://dev.to/sdorra/nextjs-13-fonts-with-tailwind-2l4l
const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-archivo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${archivo.className} ${archivo.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* <ThemeToggle /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
